config/routes.rb
Rails.application.routes.draw do
  root 'homes#index'
  devise_for :users

  resources :manufacturers, only: [:index, :new, :create]

  resources :cars, only: [:index, :new, :create]
end

app/models/car.rb
class Car < ActiveRecord::Base
  belongs_to :manufacturer

  validates :color, presence: true
  validates :mileage, presence: true
  validates :mileage, numericality: { only_integer: true }
  validates :year, presence: true
  validates :year, numericality: { only_integer: true }
  validates :year, numericality: { greater_than_or_equal_to: 1920 }

  def car_rating
    condition = ""
    if (mileage >= 500000 && year <= 2000)
      condition = "Poor"
    elsif (mileage < 500000 && mileage >= 200000) && (year > 2000 && year <= 2005)
      condition = "Fair"
    elsif (mileage < 200000 && mileage >= 30000) && (year > 2005 && year <= 2010)
      condition = "Good"
    elsif mileage >= 500000
      condition = "Poor"
    elsif mileage < 500000 && mileage >= 200000
      condition = "Fair"
    elsif mileage < 200000 && mileage >= 30000
      condition = "Good"
    else
      condition = "Excellent"
    end
    condition
  end
end

app/models/manufacturer.rb
class Manufacturer < ActiveRecord::Base
  has_many :cars

  validates :name, presence: true, uniqueness: true
  validates :country, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  def index
    @cars = Car.all
  end

  def new
    @car = Car.new
  end

  def create
    @car = Car.new(car_params)
    if @car.save
      flash[:notice] = "New car added"
      redirect_to cars_path
    else
      flash[:error] = @car.errors.full_messages.join(", ")
      render :new
    end
  end

  protected

  def car_params
    params.require(:car).permit(:color, :year, :mileage, :description, :manufacturer_id)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
end

app/controllers/manufacturers_controller.rb
class ManufacturersController < ApplicationController
  def index
    @manufacturers = Manufacturer.all
  end

  def new
    @manufacturer = Manufacturer.new
  end

  def create
    @manufacturer = Manufacturer.new(manufacturer_params)
    if @manufacturer.save
      flash[:notice] = "Manufacturer created"
      redirect_to manufacturers_path
    else
      flash[:error] = @manufacturer.errors.full_messages.join(", ")
      render :new
    end
  end

  protected

  def manufacturer_params
    params.require(:manufacturer).permit(:name, :country)
  end
end

app/views/cars/index.html.erb
<h1>Car Listings</h1>

<table>
  <tr>
    <th>Manufacturer</th>
    <th>Year</th>
    <th>Mileage</th>
    <th>Color</th>
    <th>Description</th>
    <th>Condition</th>
  </tr>
  <% @cars.each do |car| %>
    <tr>
      <td><%= car.manufacturer.name %></td>
      <td><%= car.year %></td>
      <td><%= car.mileage %></td>
      <td><%= car.color %></td>
      <td><%= car.description %></td>
      <td><%= car.car_rating %></td>
    </tr>
  <% end %>
</table>

<%= link_to "Add a Car", new_car_path %>

app/views/cars/new.html.erb
<h1>Add a Car</h1>

<%= form_for @car do |f| %>

  <%= f.label :manufacturer_id %>
    <%= f.collection_select(:manufacturer_id, Manufacturer.all, :id, :name) %>
    <br>
    <br>
    <%= f.label :year %>
    <%= f.number_field :year  %>
    <br>
    <br>
    <%= f.label :mileage %>
    <%= f.number_field :mileage  %>
    <br>
    <br>
    <%= f.label :color %>
    <%= f.text_field :color %>
    <br>
    <br>
    <%= f.label :description %>
    <%= f.text_field :description %>
    <br>
    <br>
    <%= f.submit "Submit" %>
<% end %>

<%= link_to "Back to Car Listings", cars_path %>

app/views/homes/index.html.erb
<%= link_to "Add a Manufacturer", new_manufacturer_path %>
<hr />
<%= link_to "All Manufacturers", manufacturers_path %>
<hr />
<%= link_to "Add a Car", new_car_path %>
<hr />
<%= link_to "All Cars", cars_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Carlistings</title>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= csrf_meta_tags %>
</head>
<body>

  <nav class="top-bar">
    <ul class="title-area">
      <li class="name">
        <h1><a href="/">Carlistings</a></h1>
      </li>
    </ul>

    <section class="top-bar-section">
      <ul class="right">
        <%- if current_user -%>
          <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
        <%- else -%>
          <li><%= link_to 'Sign Up', new_user_registration_path %></li>
          <li><%= link_to 'Sign In', new_user_session_path %></li>
        <%- end -%>
      </ul>
    </section>
  </nav>

  <%- flash.each do |key, value| -%>
    <div class="flash flash-<%= key %>">
      <%= value %>
    </div>
  <%- end -%>
  <div class="container large-6 columns">
    <%= yield %>
  </div>

  <%= javascript_include_tag 'application' %>
  <%= yield :extra_footer %>
</body>
</html>

app/views/manufacturers/index.html.erb
<h1>Manufacturer Listings</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Country</th>
  </tr>
  <% @manufacturers.each do |m| %>
  <tr>
    <td>
      <%= m.name %>
    </td>
    <td>
      <%= m.country %>
    </td>
  </tr>
  <% end %>
</table>

<%= link_to "Add a Manufacturer", new_manufacturer_path %>

app/views/manufacturers/new.html.erb
<h1>Enter a Manufacturer</h1>

<%= form_for @manufacturer do |f| %>
<%= f.label :name %>
<%= f.text_field :name %>

<%= f.label :country %>
<%= f.text_field :country %>

<%= f.submit "Submit" %>
<% end %>
<%= link_to "Back to Manufacturer Listings", manufacturers_path %>